import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { connectToDatabse } from "./dbConfig/dbconfig";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

connectToDatabse();
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portifilio Showcase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const pathName = typeof window !== 'undefined' ? window.location.pathname : '';
  // const isAdminRoute = pathName.startsWith('/admin');

  // // If it's an admin route, only render children without root layout styles
  // if (isAdminRoute) {
  //   return children;
  // }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {/* <VideoGallery/> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
